databases:
  - name: FineWise365
    databaseName: fin_wise_365
    user: nikhilgarg

services:
  - type: web
    name: FineWise365
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fin_wise_365
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default